### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by PerpSearch** [koillection/koillection#1262]
I'm not sure if this is a problem for anyone else, but it could just be my issue.  In using the search window in the upper left corner I could enter part of a term and it would return partial matches, now when I hit enter on a partial match it returns the "Oops" error.  If there's only one result it works though.  Short vid on what I see .    I'm running a docker container and have the same problem in either version 1.5.13 and 1.5.16.   If I'm the only one having the issue and my DB is corrupted or something, please give it some thought when you get a chance. 

https://imgur.com/Hqgr8Lt.mp4

Thanks.

**Comment by benjaminjonard** [comment]
I tried again using the same item names as you but couldn't reproduce the error.  
I don't think your database is corrupted or anything, but for the next release I'm going to add a new Administration page listing all errors. It should give more info about this problem.

**Comment by PerpSearch** [comment]
Thanks a bunch.

**Comment by PerpSearch** [comment]
I'm not trying to push, but when might that next release release?  I'm getting more errors now.  When I edit an existing record, it comes back w/ an error regarding duplicated fields and there's a duplicated filed that wasn't there until I tried to save the edit. This is on 1.5.13 so I'll see how bad 1.5.16 is again. Thanks again and have a enjoyable holiday.

**Comment by benjaminjonard** [comment]
I published a new version with the new admin page with errors. Hopefully we can get more details about this issue

**Comment by PerpSearch** [comment]
I really appreciate you're work here and look forward to checking out 1.6.0, but it may be a bit before I can as Synology has not released PHP8.4.  I've going to try to figure out if I can do that myself, but like most tech at this level, the learning curve is long.  I will continue to poke at it to see if I can figure some of it out.  That said, I did post some additional info [here](https://github.com/benjaminjonard/koillection/issues/1267) that might shed additional light on my issues.

Thanks again and I'll keep you posted

C

**Comment by PerpSearch** [comment]
The admin page works great. The following is the resulting errors. I've attached a screen capture of the report
 
![2024-12-29_121504](https://github.com/user-attachments/assets/4e6afcde-bc4e-4816-876e-dee0b39dc1dd)

and the following are the errors in detail.  I'll continue to try different things to see what all is broken.  (Had a forth one more) Nice work on this.


**FIRST**

2024-12-29 12:10:21 500 CRITICAL Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unsupported operand types: array + int")." at _collections_grid.html.twig line 2

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Extension/CoreExtension.php -> render() (line 1482)

in /var/www/koillection/var/cache/prod/twig/f8/f8601a65ae14a43adbdd79d6c1e9d0c2.php -> include() (line 229)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_content() (line 431)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yieldBlock() (line 231)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_body() (line 431)

in /var/www/koillection/var/cache/prod/twig/ae/ae47aa8f7efce0d3a2ca38ddac9f7524.php -> yieldBlock() (line 173)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yield() (line 51)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/f8/f8601a65ae14a43adbdd79d6c1e9d0c2.php -> yield() (line 52)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Environment.php -> render() (line 320)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> render() (line 431)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRenderView() (line 436)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRender() (line 250)

in /var/www/koillection/src/Controller/SearchController.php -> render() (line 67)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> index() (line 183)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw() (line 76)

in /var/www/koillection/vendor/symfony/http-kernel/Kernel.php -> handle() (line 182)

in /var/www/koillection/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle() (line 35)

in /var/www/koillection/vendor/autoload_runtime.php -> run() (line 29)

in /var/www/koillection/public/index.php -> require_once(/var/www/koillection/vendor/autoload_runtime.php) (line 5) 

**SECOND**

2024-12-29 12:07:59 500 CRITICAL Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("App\Service\CachedValuesGetter::getCachedValues(): Argument #1 ($entity) must be of type App\Entity\Collection|App\Entity\Album|App\Entity\Wishlist, App\Entity\Item given, called in /var/www/koillection/src/Service/ArraySorter.php on line 74")." at _items_grid.html.twig line 2

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Extension/CoreExtension.php -> render() (line 1482)

in /var/www/koillection/var/cache/prod/twig/f8/f8601a65ae14a43adbdd79d6c1e9d0c2.php -> include() (line 211)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_content() (line 431)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yieldBlock() (line 231)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_body() (line 431)

in /var/www/koillection/var/cache/prod/twig/ae/ae47aa8f7efce0d3a2ca38ddac9f7524.php -> yieldBlock() (line 173)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yield() (line 51)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/f8/f8601a65ae14a43adbdd79d6c1e9d0c2.php -> yield() (line 52)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Environment.php -> render() (line 320)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> render() (line 431)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRenderView() (line 436)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRender() (line 250)

in /var/www/koillection/src/Controller/SearchController.php -> render() (line 67)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> index() (line 183)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw() (line 76)

in /var/www/koillection/vendor/symfony/http-kernel/Kernel.php -> handle() (line 182)

in /var/www/koillection/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle() (line 35)

in /var/www/koillection/vendor/autoload_runtime.php -> run() (line 29)

in /var/www/koillection/public/index.php -> require_once(/var/www/koillection/vendor/autoload_runtime.php) (line 5) 

**THIRD**

2024-12-29 12:07:41 500 CRITICAL Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unsupported operand types: array + int")." at _collections_grid.html.twig line 14

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Extension/CoreExtension.php -> render() (line 1482)

in /var/www/koillection/var/cache/prod/twig/e8/e8d2b93a753df7df1bc234c70ce02ae8.php -> include() (line 400)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_content() (line 431)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yieldBlock() (line 231)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_body() (line 431)

in /var/www/koillection/var/cache/prod/twig/ae/ae47aa8f7efce0d3a2ca38ddac9f7524.php -> yieldBlock() (line 173)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yield() (line 51)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/e8/e8d2b93a753df7df1bc234c70ce02ae8.php -> yield() (line 54)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Environment.php -> render() (line 320)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> render() (line 431)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRenderView() (line 436)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRender() (line 250)

in /var/www/koillection/src/Controller/CollectionController.php -> render() (line 141)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> show() (line 183)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw() (line 76)

in /var/www/koillection/vendor/symfony/http-kernel/Kernel.php -> handle() (line 182)

in /var/www/koillection/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle() (line 35)

in /var/www/koillection/vendor/autoload_runtime.php -> run() (line 29)

in /var/www/koillection/public/index.php -> require_once(/var/www/koillection/vendor/autoload_runtime.php) (line 5)

**FORTH**

2024-12-29 12:07:41 500 CRITICAL Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unsupported operand types: array + int")." at _collections_grid.html.twig line 14

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Extension/CoreExtension.php -> render() (line 1482)

in /var/www/koillection/var/cache/prod/twig/e8/e8d2b93a753df7df1bc234c70ce02ae8.php -> include() (line 400)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_content() (line 431)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yieldBlock() (line 231)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_body() (line 431)

in /var/www/koillection/var/cache/prod/twig/ae/ae47aa8f7efce0d3a2ca38ddac9f7524.php -> yieldBlock() (line 173)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yield() (line 51)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/var/cache/prod/twig/e8/e8d2b93a753df7df1bc234c70ce02ae8.php -> yield() (line 54)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343)

in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358)

in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35)

in /var/www/koillection/vendor/twig/twig/src/Environment.php -> render() (line 320)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> render() (line 431)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRenderView() (line 436)

in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRender() (line 250)

in /var/www/koillection/src/Controller/CollectionController.php -> render() (line 141)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> show() (line 183)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw() (line 76)

in /var/www/koillection/vendor/symfony/http-kernel/Kernel.php -> handle() (line 182)

in /var/www/koillection/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle() (line 35)

in /var/www/koillection/vendor/autoload_runtime.php -> run() (line 29)

in /var/www/koillection/public/index.php -> require_once(/var/www/koillection/vendor/autoload_runtime.php) (line 5)

**Comment by benjaminjonard** [comment]
I'll have a closer look tomorrow. The good news is that it's the same problem occurring in different places.

Could you just try going to the Administration page and clicking on 'Refresh caches' at the bottom?

**Comment by PerpSearch** [comment]
Refreshed cashes and it replied "Cashes successfully refreshed"

and I tried moving some things around to see if I can change anything.  I moved several items from one collection to another and now I'm getting the folllowing error as well. 

Get some rest. It's probably been a long day on your end.
Thanks
Charley

2024-12-29 13:37:16 500 CRITICAL Uncaught PHP Exception TypeError: "Unsupported operand types: array + int" at CachedValuesGetter.php line 94

in /var/www/koillection/src/Service/CachedValuesGetter.php -> mergeAndAdd() (line 39)

in /var/www/koillection/src/Service/CachedValuesGetter.php -> getForCollection() (line 23)

in /var/www/koillection/src/Controller/CollectionController.php -> getCachedValues() (line 41)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> index() (line 183)

in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw() (line 76)

in /var/www/koillection/vendor/symfony/http-kernel/Kernel.php -> handle() (line 182)

in /var/www/koillection/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle() (line 35)

in /var/www/koillection/vendor/autoload_runtime.php -> run() (line 29)

in /var/www/koillection/public/index.php -> require_once(/var/www/koillection/vendor/autoload_runtime.php) (line 5)

**Comment by benjaminjonard** [comment]
I published a new release, could you tell me if it fixes your issue ?

**Comment by PerpSearch** [comment]
Wow, it fixed some of it. I can now access that collection that was throwing an error. The search is still screwed up though. The error reporting is working well I believe. This is the one I got just now doing that search. 


 2024-12-30 10:06:099500CRITICALUncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("App\Service\CachedValuesGetter::getCachedValues(): Argument #1 ($entity) must be of type App\Entity\Collection|App\Entity\Album|App\Entity\Wishlist, App\Entity\Item given, called in /var/www/koillection/src/Service/ArraySorter.php on line 74")." at _items_grid.html.twig line 2

When I try to select the view for this error, it returns the content from a different error line though. This is was comes back but the time stamp is from the error above. I'll try again from my desktop to see if that makes a difference. 

2024-12-29 12:07:59 500 CRITICAL Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("App\Service\CachedValuesGetter::getCachedValues(): Argument #1 ($entity) must be of type App\Entity\Collection|App\Entity\Album|App\Entity\Wishlist, App\Entity\Item given, called in /var/www/koillection/src/Service/ArraySorter.php on line 74")." at _items_grid.html.twig line 2 

in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358) 


in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35) 


in /var/www/koillection/vendor/twig/twig/src/Extension/CoreExtension.php -> render() (line 1482) 


in /var/www/koillection/var/cache/prod/twig/f8/f8601a65ae14a43adbdd79d6c1e9d0c2.php -> include() (line 211) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_content() (line 431) 


in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yieldBlock() (line 231) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> block_body() (line 431) 


in /var/www/koillection/var/cache/prod/twig/ae/ae47aa8f7efce0d3a2ca38ddac9f7524.php -> yieldBlock() (line 173) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387) 


in /var/www/koillection/var/cache/prod/twig/17/173fee83d3192309adf1588adb1725fd.php -> yield() (line 51) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387) 


in /var/www/koillection/var/cache/prod/twig/f8/f8601a65ae14a43adbdd79d6c1e9d0c2.php -> yield() (line 52) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> doDisplay() (line 387) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> yield() (line 343) 


in /var/www/koillection/vendor/twig/twig/src/Template.php -> display() (line 358) 


in /var/www/koillection/vendor/twig/twig/src/TemplateWrapper.php -> render() (line 35) 


in /var/www/koillection/vendor/twig/twig/src/Environment.php -> render() (line 320) 


in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> render() (line 431) 


in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRenderView() (line 436) 


in /var/www/koillection/vendor/symfony/framework-bundle/Controller/AbstractController.php -> doRender() (line 250) 


in /var/www/koillection/src/Controller/SearchController.php -> render() (line 67) 


in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> index() (line 183) 


in /var/www/koillection/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw() (line 76) 


in /var/www/koillection/vendor/symfony/http-kernel/Kernel.php -> handle() (line 182) 


in /var/www/koillection/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle() (line 35) 


in /var/www/koillection/vendor/autoload_runtime.php -> run() (line 29) 


in /var/www/koillection/public/index.php -> require_once(/var/www/koillection/vendor/autoload_runtime.php) (line 5) 


Same result on my desktop.  I can see the time stamp is 2024-12-30 10:30:34 but when I select the Detail, the error returned is from 2024-12-29 12:07:59 

Hope that helps.

**Comment by benjaminjonard** [comment]
There's a new version available. I couldn't reproduce but I think I could guess what's happening

**Comment by PerpSearch** [comment]
That fixed it. Works like a champ.  Do you have a Venmo or something? I'd love to buy you a coffee.

**Comment by PerpSearch** [comment]
You guessed correctly.  I can access all the records and the search works
like a charm.
I'm still not convinced it wasn't something I did, but whatever it was,
it's not a problem any more.
You have a venmo or paypal link?
